on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main
    with:
      clippy_default: false
      clippy_args: --all-features

  analyze:
    name: Dusk Analyzer
    uses: dusk-network/.github/.github/workflows/dusk-analysis.yml@main

  build_benches:
    name: Build Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo bench --all-features --no-run

  check_encryption:
    name: Check encryption compiles without zk
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --features=encryption --no-run

  test_all:
    name: Tests all
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main
    with:
      test_flags: --all-features
